import { ArtistRequest, SongItem, UserRecord } from './admin.models';

export const ADMIN_SONGS: SongItem[] = [
  {
    id: 'S001',
    title: 'Đêm thành phố',
    album: 'Sau hoàng hôn',
    artist: 'Dưa lưới',
    thumbnail:
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?q=80&w=300&auto=format&fit=crop',
    source: 'LOCAL',
    duration: '04:05',
    createdAt: '10/04/2026 08:30',
    status: 'Pending',
    audioUrl: 'assets/audio/demo-song.mp3',
  },
  {
    id: 'S002',
    title: 'Giai điệu mơ',
    album: 'Mùa yêu',
    artist: 'Khánh Beat',
    thumbnail:
      'https://images.unsplash.com/photo-1516280440614-37939bbacd81?q=80&w=300&auto=format&fit=crop',
    source: 'ITUNES',
    duration: '03:28',
    createdAt: '09/04/2026 18:10',
    status: 'Approved',
    audioUrl: 'assets/audio/demo-song.mp3',
  },
  {
    id: 'S003',
    title: 'Ly trà xanh',
    album: 'Tình ca',
    artist: 'Hồng Nhung',
    thumbnail:
      'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?q=80&w=300&auto=format&fit=crop',
    source: 'LOCAL',
    duration: '03:45',
    createdAt: '08/04/2026 12:00',
    status: 'Rejected',
    audioUrl: 'assets/audio/demo-song.mp3',
    rejectReason: 'Chất lượng file audio chưa đạt yêu cầu.',
  },
  {
    id: 'S004',
    title: 'Phố khuya',
    album: 'Đêm không ngủ',
    artist: 'Hoàng Acoustic',
    thumbnail:
      'https://images.unsplash.com/photo-1507838153414-b4b713384a76?q=80&w=300&auto=format&fit=crop',
    source: 'ITUNES',
    duration: '04:12',
    createdAt: '07/04/2026 21:15',
    status: 'Hidden',
    audioUrl: 'assets/audio/demo-song.mp3',
  },
];

export const ADMIN_USERS: UserRecord[] = [
  {
    id: 'U001',
    name: 'Nguyễn Hoàng',
    username: 'nguyenhoang',
    email: 'hoang@example.com',
    avatar: 'https://i.pravatar.cc/100?img=1',
    role: 'USER',
    status: 'Active',
    createdAt: '01/03/2026',
    playlistCount: 4,
    likedSongsCount: 26,
  },
  {
    id: 'U002',
    name: 'Trần Minh',
    username: 'tranminh',
    email: 'minh@example.com',
    avatar: 'https://i.pravatar.cc/100?img=2',
    role: 'ARTIST',
    status: 'Active',
    createdAt: '12/03/2026',
    playlistCount: 2,
    likedSongsCount: 18,
  },
  {
    id: 'U003',
    name: 'Quản trị viên',
    username: 'admin',
    email: 'admin@melono.local',
    avatar: 'https://ui-avatars.com/api/?name=Admin&background=1ed760&color=fff',
    role: 'ADMIN',
    status: 'Active',
    createdAt: '01/02/2026',
    playlistCount: 0,
    likedSongsCount: 0,
  },
  {
    id: 'U004',
    name: 'Hồng Nhung',
    username: 'hongnhung',
    email: 'nhung@example.com',
    avatar: 'https://i.pravatar.cc/100?img=4',
    role: 'USER',
    status: 'Banned',
    createdAt: '21/03/2026',
    playlistCount: 1,
    likedSongsCount: 11,
    banReason: 'Spam nội dung không phù hợp.',
  },
];

export const ADMIN_ARTIST_REQUESTS: ArtistRequest[] = [
  {
    id: 'AR001',
    userId: 'U001',
    userName: 'Nguyễn Hoàng',
    email: 'hoang@example.com',
    avatar: 'https://i.pravatar.cc/100?img=1',
    stageName: 'Hoàng Acoustic',
    genre: 'Acoustic',
    bio: 'Ca sĩ tự do theo đuổi dòng nhạc acoustic và indie, thường biểu diễn tại các sân khấu nhỏ.',
    createdAt: '09/04/2026',
    status: 'Pending',
  },
  {
    id: 'AR002',
    userId: 'U002',
    userName: 'Trần Minh',
    email: 'minh@example.com',
    avatar: 'https://i.pravatar.cc/100?img=2',
    stageName: 'Khánh Beat',
    genre: 'Rap',
    bio: 'Sáng tác và sản xuất các ca khúc rap, đã có một số sản phẩm tự phát hành.',
    createdAt: '08/04/2026',
    status: 'Approved',
  },
  {
    id: 'AR003',
    userId: 'U004',
    userName: 'Hồng Nhung',
    email: 'nhung@example.com',
    avatar: 'https://i.pravatar.cc/100?img=4',
    stageName: 'Hồng Nhung',
    genre: 'Pop',
    bio: 'Ca sĩ trẻ định hướng pop ballad, có kinh nghiệm cover và trình diễn trên mạng xã hội.',
    createdAt: '07/04/2026',
    status: 'Rejected',
    rejectReason: 'Thông tin hồ sơ nghệ sĩ chưa đầy đủ.',
  },
];
