import { ArtistRequest, SongItem, UserRecord } from './admin.models';

export const ADMIN_SONGS: SongItem[] = [];

export const ADMIN_USERS: UserRecord[] = [
  {
    id: 'U001',
    name: 'Nguyễn Hoàng',
    username: 'nguyenhoang',
    email: 'hoang@example.com',
    avatar: 'https://i.pravatar.cc/100?img=1',
    role: 'USER',
    status: 'Active',
    createdAt: '01/03/2026',
    playlistCount: 4,
    likedSongsCount: 26,
  },
  {
    id: 'U002',
    name: 'Trần Minh',
    username: 'tranminh',
    email: 'minh@example.com',
    avatar: 'https://i.pravatar.cc/100?img=2',
    role: 'ARTIST',
    status: 'Active',
    createdAt: '12/03/2026',
    playlistCount: 2,
    likedSongsCount: 18,
  },
  {
    id: 'U003',
    name: 'Quản trị viên',
    username: 'admin',
    email: 'admin@melono.local',
    avatar: 'https://ui-avatars.com/api/?name=Admin&background=1ed760&color=fff',
    role: 'ADMIN',
    status: 'Active',
    createdAt: '01/02/2026',
    playlistCount: 0,
    likedSongsCount: 0,
  },
  {
    id: 'U004',
    name: 'Hồng Nhung',
    username: 'hongnhung',
    email: 'nhung@example.com',
    avatar: 'https://i.pravatar.cc/100?img=4',
    role: 'USER',
    status: 'Banned',
    createdAt: '21/03/2026',
    playlistCount: 1,
    likedSongsCount: 11,
    banReason: 'Spam nội dung không phù hợp.',
  },
];

export const ADMIN_ARTIST_REQUESTS: ArtistRequest[] = [
  {
    id: 'AR001',
    userId: 'U001',
    userName: 'Nguyễn Hoàng',
    email: 'hoang@example.com',
    avatar: 'https://i.pravatar.cc/100?img=1',
    stageName: 'Hoàng Acoustic',
    genre: 'Acoustic',
    bio: 'Ca sĩ tự do theo đuổi dòng nhạc acoustic và indie, thường biểu diễn tại các sân khấu nhỏ.',
    createdAt: '09/04/2026',
    status: 'Pending',
  },
  {
    id: 'AR002',
    userId: 'U002',
    userName: 'Trần Minh',
    email: 'minh@example.com',
    avatar: 'https://i.pravatar.cc/100?img=2',
    stageName: 'Khánh Beat',
    genre: 'Rap',
    bio: 'Sáng tác và sản xuất các ca khúc rap, đã có một số sản phẩm tự phát hành.',
    createdAt: '08/04/2026',
    status: 'Approved',
  },
  {
    id: 'AR003',
    userId: 'U004',
    userName: 'Hồng Nhung',
    email: 'nhung@example.com',
    avatar: 'https://i.pravatar.cc/100?img=4',
    stageName: 'Hồng Nhung',
    genre: 'Pop',
    bio: 'Ca sĩ trẻ định hướng pop ballad, có kinh nghiệm cover và trình diễn trên mạng xã hội.',
    createdAt: '07/04/2026',
    status: 'Rejected',
    rejectReason: 'Thông tin hồ sơ nghệ sĩ chưa đầy đủ.',
  },
];
